# -*- coding: utf-8 -*-
"""Laguardia data

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cXRx_x0MjhRbfuMdm5fhqln1BZd-kilk
"""

#this notebook shows the steps we went through to create a dataset that has the airline, hotel prices, and weather data
import pandas as pd
import numpy as np

# Cleaning up Weather_grouped data
wea= pd.read_csv('Weather_Grouped.csv')

wea.head()

wea['Start_Time'] = wea['Start_Time'].astype(str)

#Seting 'Month' column to match "Period" column in the Hotal_Grouped.csv so we can merge the 2 datasets
wea['Period'] = wea['Start_Time'].apply(lambda x: "M" + x[-5:-3])

wea.head()

wea.tail()

# Importing Hotel_Grouped.csv and droping unneeded columns
rfr= pd.read_csv('Hotel_Grouped.csv')

columns_to_drop = ['Series ID','Unnamed: 0']

rfr = rfr.drop(columns=columns_to_drop)

rfr.head()

wea.to_csv('Weather_Grouped2.csv')

# Merging Weather_Grouped and Hotel_Grouped datasets


weather_df = pd.read_csv('Weather_Grouped2.csv')

merged_df = pd.merge(rfr, weather_df, on='Period')

print(merged_df.head())

merged_df.tail()

print(merged_df.columns)

# droping uneeded columns
columns_to_drop = ['Unnamed: 0.2', 'Unnamed: 0.1']

merged_df = merged_df.drop(columns=columns_to_drop)

print(merged_df.head())

#renaming column to match the date column in the LaGuardia_CLEANED_UPDATE2.csv
merged_df = merged_df.rename(columns={'Start_Time': 'Date'})

merged_df.to_csv('Weather.Prices2.csv')

nyc= pd.read_csv('LaGuardia_CLEANED_UPDATE2.csv')

nyc.head()

#Merging both data sets to create one big file that shows airline info, hotel price info, and weather info.
all_df = pd.merge(merged_df, nyc, on='Date')

print(all_df.head())

#downloading copy of the created dataset
all_df.to_csv('LaGuardia.Weather.Prices.csv')

all_df.tail()

# reading in the weather_data.xlsx, this is the data from the weather API key we are using.
#We will merge it with the data set we created to get more in-deph info about the weather

file_path = 'weather_data.xlsx'

wd_df = pd.read_excel(file_path)

print(wd_df)

#renaming 'date' column in the weather_data file to match the "Date" column in the LaGuardia.Weather.Price data we created
wd_df = wd_df.rename(columns={'date': 'Date'})

all_df['Date'] = pd.to_datetime(all_df['Date'])


merged_df = pd.merge(all_df, wd_df, on='Date')

print(merged_df.head())

# downloading the merged data file we created into a csv

merged_df.to_csv('LaGuardia_All_Dataupdate.csv')

print(merged_df.columns)

merged_df.head()